name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Rebuild app
      run: npm run docker:build

    - name: Stop app
      run: npm run docker:stop

    - name: Start app
      run: npm run docker:start